//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMT_DATN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietTrangThaiDonHang
    {
        public int FK_MaDonHang { get; set; }
        public int FK_MaTrangThaiDonHang { get; set; }
        public System.DateTime ThoiGianCapNhat { get; set; }
        public System.Guid FK_MaNhanVienCapNhat { get; set; }
    
        public virtual tblDonHang tblDonHang { get; set; }
        public virtual tblNguoiDung tblNguoiDung { get; set; }
        public virtual tblTrangThaiDonHang tblTrangThaiDonHang { get; set; }
    }
}
