//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMT_DATN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNguoiDung()
        {
            this.tblDanhGiaSanPhams = new HashSet<tblDanhGiaSanPham>();
            this.tblDonHangs = new HashSet<tblDonHang>();
            this.tblDonHangs1 = new HashSet<tblDonHang>();
            this.tblPhieuNhaps = new HashSet<tblPhieuNhap>();
        }
    
        public System.Guid PK_MaNguoiDung { get; set; }
        public string TenNguoiDung { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string TenDangNhap { get; set; }
        public string MaSalt { get; set; }
        public string MatKhauDaMaHoa { get; set; }
        public bool TinhTrangHoatDong { get; set; }
        public int FK_MaQuyen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDanhGiaSanPham> tblDanhGiaSanPhams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDonHang> tblDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDonHang> tblDonHangs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPhieuNhap> tblPhieuNhaps { get; set; }
        public virtual tblQuyen tblQuyen { get; set; }
    }
}
